'use client'
import React, { useState, useRef, useMemo } from 'react'
import {
  X, User, BookOpen, Users, ChevronRight, ChevronLeft,
  AlertCircle, CheckCircle, Camera, FileText, Trash2, 
  Activity, CheckSquare, Search, UploadCloud
} from 'lucide-react'
import { useCreateAdmissionMutation } from '@/src/store/api/admissionApi'
import { useListClassesQuery } from '@/src/store/api/classApi'
import { useListSectionsQuery } from '@/src/store/api/sectionApi'
import { useListParentsQuery } from '@/src/store/api/parentApi'
import Swal from 'sweetalert2'
import { GENDER_OPTIONS, BLOOD_GROUPS, ACADEMIC_STATUSES } from './studentUtils'

// ── Shared Config ──────────────────────────────────────────────────────────
const COMMON_ALLERGIES = ['Peanuts', 'Dairy', 'Shellfish', 'Eggs', 'Soy', 'Wheat', 'Tree Nuts', 'None']

const STEPS = [
  { id: 1, label: 'Personal',  icon: User },
  { id: 2, label: 'Academic',  icon: BookOpen },
  { id: 3, label: 'Guardian',  icon: Users },
  { id: 4, label: 'Background', icon: Activity },
  { id: 5, label: 'Documents', icon: FileText },
  { id: 6, label: 'Review',    icon: CheckSquare },
]

function Field({ label, required, helpText, children }: { label: React.ReactNode; required?: boolean; helpText?: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-1">
      <label className="text-xs font-semibold text-[var(--foreground-muted)] uppercase tracking-wide">
        {label}{required && <span className="text-[var(--danger)] ml-0.5">*</span>}
      </label>
      {children}
      {helpText && <span className="text-[10px] text-[var(--foreground-muted)]">{helpText}</span>}
    </div>
  )
}

interface Props { onClose: () => void }

export default function StudentForm({ onClose }: Props) {
  const [step, setStep] = useState(1)
  const [error, setError] = useState('')

  const [createAdmission, { isLoading }] = useCreateAdmissionMutation()
  
  // ── Queries ───────────────────────────────────────────────────────────────
  const { data: classData } = useListClassesQuery({ limit: 200 })
  const { data: sectionData } = useListSectionsQuery({ limit: 500 })
  
  const [parentSearch, setParentSearch] = useState('')
  const { data: parentData, isFetching: isSearchingParents } = useListParentsQuery(
    { limit: 10, search: parentSearch },
    { skip: !parentSearch, refetchOnMountOrArgChange: true }
  )

  const classes = [...(classData?.data ?? classData?.result ?? [])].sort((a: any, b: any) => a.numericLevel - b.numericLevel)
  const parents = [...(parentData?.data ?? parentData?.result ?? [])]

  // ── Form State ────────────────────────────────────────────────────────────
  // Step 1
  const [personal, setPersonal] = useState({
    firstName: '', surname: '', email: '', phone: '',
    gender: 'male', dateOfBirth: '', bloodGroup: '',
  })
  
  // Step 2
  const [academic, setAcademic] = useState({
    className: '', section: '', dateOfAdmission: new Date().toISOString().split('T')[0]
    // Note: Admission number is auto-generated by the backend.
  })
  
  const allSections = [...(sectionData?.data ?? sectionData?.result ?? [])]
  const availableSections = allSections.filter((s: any) => s.class?.name === academic.className)

  // Step 3
  const [address, setAddress] = useState({
    country: 'Nepal', province: '', district: '', municipality: '', wardNo: '', tole: '', houseNo: '', postCode: '',
    isTemporarySame: true,
    tempCountry: 'Nepal', tempProvince: '', tempDistrict: '', tempMunicipality: '', tempWardNo: '', tempTole: '', tempHouseNo: '', tempPostCode: ''
  })
  
  const [guardianMode, setGuardianMode] = useState<'new' | 'existing'>('new')
  const [selectedParentUser, setSelectedParentUser] = useState<any>(null)
  
  const [guardian, setGuardian] = useState({
    father: { name: '', email: '', phone: '', occupation: '', qualification: '' },
    mother: { name: '', email: '', phone: '', occupation: '', qualification: '' },
    guardian: { name: '', email: '', phone: '', relation: '' },
    emergencyContact: 'father',
  })

  // Step 4
  const [background, setBackground] = useState({
    allergies: [] as string[], allergiesOther: '',
    medicalHistory: '', specificAilments: '', surgeryHistory: '',
    specialInstructions: '', previousSchooling: 'No', familyAtThisSchool: 'No'
  })

  // Step 5
  type DocKey = 'profileImage' | 'birthCertificate' | 'parentId' | 'prevAcademicCert' | 'transferCert' | 'parentPhoto'
  const [docs, setDocs] = useState<Record<DocKey, File | null>>({
    profileImage: null, birthCertificate: null, parentId: null, prevAcademicCert: null, transferCert: null, parentPhoto: null
  })
  const [profilePreview, setProfilePreview] = useState<string | null>(null)

  // Step 6
  const [declaration, setDeclaration] = useState(false)

  // Helpers
  const sp = (k: string, v: string) => setPersonal(p => ({ ...p, [k]: v }))
  const sa = (k: string, v: string) => setAcademic(a => ({ ...a, [k]: v }))
  const sd = (k: string, v: any) => setAddress(a => ({ ...a, [k]: v }))
  const sDocs = (key: DocKey, file: File | null) => setDocs(prev => ({ ...prev, [key]: file }))

  // ── Validation ────────────────────────────────────────────────────────────
  const validateStep = (): boolean => {
    setError('')
    if (step === 1) {
      if (!personal.firstName.trim()) { setError('First name is required'); return false }
      if (!personal.surname.trim())   { setError('Surname is required'); return false }
      if (!personal.email.trim())     { setError('Email is required'); return false }
      if (!personal.gender)           { setError('Gender is required'); return false }
    }
    if (step === 2) {
      if (!academic.className) { setError('Class is required'); return false }
    }
    if (step === 3) {
      if (!address.province || !address.district || !address.municipality) {
        setError('Province, District, and Municipality are required for permanent address.'); return false
      }
      if (!address.isTemporarySame && (!address.tempProvince || !address.tempDistrict || !address.tempMunicipality)) {
        setError('Temporary address fields are compulsory if not same as permanent.'); return false
      }
      
      if (guardianMode === 'existing') {
        if (!selectedParentUser) { setError('Please search and attach an existing parent profile.'); return false }
      } else {
        if (!guardian.father.name && !guardian.mother.name && !guardian.guardian.name) {
          setError('At least one parent/guardian information (Name) is required.'); return false
        }
      }
    }
    if (step === 4) {
      // Background fields are mostly optional.
    }
    if (step === 5) {
      if (!docs.profileImage) { setError('Student Passport Photo is required'); return false }
      if (!docs.birthCertificate) { setError('Birth Certificate is required'); return false }
      if (!docs.parentId) { setError('Parent/Guardian ID is required'); return false }
    }
    return true
  }

  const next = () => { if (validateStep()) setStep(s => s + 1) }
  const prev = () => { setError(''); setStep(s => s - 1) }

  // ── Submit ────────────────────────────────────────────────────────────────
  const handleSubmit = async () => {
    if (!declaration) { setError('You must agree to the declaration to submit.'); return }
    if (!validateStep()) return

    const fd = new FormData()
    
    // 1. Personal
    fd.append('firstName', personal.firstName)
    fd.append('surname', personal.surname)
    fd.append('email', personal.email)
    fd.append('phone', personal.phone || '')
    fd.append('gender', personal.gender)
    if (personal.dateOfBirth) fd.append('dateOfBirth', personal.dateOfBirth)
    if (personal.bloodGroup) fd.append('bloodGroup', personal.bloodGroup)

    // 2. Academic
    fd.append('className', academic.className)
    fd.append('section', academic.section || '')
    fd.append('dateOfAdmission', academic.dateOfAdmission || '')
    fd.append('academicStatus', 'admitted') // fixed backend default status

    // 3. Address & Guardian
    const addressPayload = {
      country: address.country, province: address.province, district: address.district,
      municipality: address.municipality, wardNo: address.wardNo, tole: address.tole,
      houseNo: address.houseNo, postCode: address.postCode,
      isTemporarySame: address.isTemporarySame,
      tempCountry: address.tempCountry, tempProvince: address.tempProvince, tempDistrict: address.tempDistrict,
      tempMunicipality: address.tempMunicipality, tempWardNo: address.tempWardNo, tempTole: address.tempTole,
      tempHouseNo: address.tempHouseNo, tempPostCode: address.tempPostCode,
    }
    fd.append('address', JSON.stringify(addressPayload))

    if (guardianMode === 'existing' && selectedParentUser) {
      // Backend uses email to find existing parent
      fd.append('father', JSON.stringify({ email: selectedParentUser.user?.email || selectedParentUser.email }))
      fd.append('familyInfo', JSON.stringify({ emergencyContact: 'father' })) // Default logic
    } else {
      if (guardian.father.name)   fd.append('father',   JSON.stringify(guardian.father))
      if (guardian.mother.name)   fd.append('mother',   JSON.stringify(guardian.mother))
      if (guardian.guardian.name) fd.append('guardian', JSON.stringify(guardian.guardian))
      fd.append('familyInfo', JSON.stringify({ emergencyContact: guardian.emergencyContact }))
    }

    // 4. Background
    const bgPayload = {
      ...background,
      allergies: [...background.allergies, ...(background.allergiesOther ? [background.allergiesOther] : [])]
    }
    fd.append('background', JSON.stringify(bgPayload))

    // 5. Documents
    if (docs.profileImage) fd.append('profileImage', docs.profileImage)
    // Map extra documentation files generically
    Object.entries(docs).forEach(([key, file]) => {
      if (key !== 'profileImage' && file) {
        // We will append to 'documents' array with the original name marking the type
        const newFile = new File([file], `${key}_${file.name}`, { type: file.type })
        fd.append('documents', newFile)
      }
    })

    fd.append('declarationSigned', 'true')

    try {
      await createAdmission(fd).unwrap()
      await Swal.fire({
        background: 'var(--card-bg)', color: 'var(--foreground)',
        icon: 'success',
        title: 'Admission Successful!',
        html: `<p>${personal.firstName} ${personal.surname} has been formally admitted.</p><p class="text-xs text-var(--foreground-muted) mt-2">The Admission No & Student ID have been system-generated.</p>`,
        timer: 3000, showConfirmButton: false,
      })
      onClose()
    } catch (err: any) {
      setError(err?.data?.message ?? 'Failed to create admission. Please try again.')
    }
  }

  // ── Handlers ──────────────────────────────────────────────────────────────
  const toggleAllergy = (a: string) => {
    setBackground(p => ({
      ...p,
      allergies: p.allergies.includes(a) ? p.allergies.filter(x => x !== a) : [...p.allergies, a]
    }))
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-fade-in p-2 sm:p-4">
      <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-2xl shadow-2xl w-full max-w-4xl flex flex-col max-h-[95vh]">

        {/* ── Header ── */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--border)] shrink-0">
          <div>
            <h2 className="font-bold text-lg text-[var(--foreground)]">New Student Admission</h2>
            <p className="text-xs text-[var(--foreground-muted)] mt-0.5">Step {step} of {STEPS.length}: {STEPS[step-1].label}</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[var(--surface-raised)] text-[var(--foreground-muted)] transition-colors">
            <X size={18} />
          </button>
        </div>

        {/* ── Step Indicator ── */}
        <div className="flex items-center px-6 py-3 bg-[var(--surface-raised)] border-b border-[var(--border)] shrink-0 overflow-x-auto no-scrollbar">
          {STEPS.map((s, i) => {
            const done = step > s.id
            const active = step === s.id
            const Icon = s.icon
            return (
              <React.Fragment key={s.id}>
                <div className="flex items-center gap-2 shrink-0">
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold transition-all ${
                    done   ? 'bg-emerald-500 text-white' :
                    active ? 'bg-[var(--primary)] text-white' :
                             'bg-[var(--border)] text-[var(--foreground-muted)]'
                  }`}>
                    {done ? <CheckCircle size={14} /> : <Icon size={13} />}
                  </div>
                  <span className={`text-xs font-semibold hidden md:block ${active ? 'text-[var(--primary)]' : done ? 'text-emerald-600' : 'text-[var(--foreground-muted)]'}`}>
                    {s.label}
                  </span>
                </div>
                {i < STEPS.length - 1 && (
                  <div className={`flex-1 min-w-[20px] h-px mx-2 md:mx-4 ${step > s.id ? 'bg-emerald-400' : 'bg-[var(--border)]'}`} />
                )}
              </React.Fragment>
            )
          })}
        </div>

        {/* ── Content ── */}
        <div className="overflow-y-auto flex-1 px-4 py-5 sm:px-6">
          
          {/* STEP 1: Personal */}
          {step === 1 && (
            <div className="flex flex-col gap-5 animate-fade-in">
              <div className="p-3 bg-[var(--primary-light)] border border-[var(--primary)] border-opacity-20 rounded-xl flex items-center gap-3">
                <AlertCircle size={18} className="text-[var(--primary)] shrink-0" />
                <p className="text-xs text-[var(--primary)] font-medium">System Auto-Generation: Admission Number &amp; Student ID will be dynamically generated and assigned upon successful enrollment.</p>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Field label="First Name" required>
                  <input className="erp-input" value={personal.firstName} onChange={e => sp('firstName', e.target.value)} placeholder="e.g. Ram" autoFocus />
                </Field>
                <Field label="Surname" required>
                  <input className="erp-input" value={personal.surname} onChange={e => sp('surname', e.target.value)} placeholder="e.g. Sharma" />
                </Field>
                <Field label="Email Address" required helpText="Student's email account">
                  <input className="erp-input" type="email" value={personal.email} onChange={e => sp('email', e.target.value)} placeholder="student@email.com" />
                </Field>
                <Field label="Phone Contact">
                  <input className="erp-input" type="tel" value={personal.phone} onChange={e => sp('phone', e.target.value)} placeholder="98XXXXXXXX" />
                </Field>
                <Field label="Gender" required>
                  <select className="erp-input" value={personal.gender} onChange={e => sp('gender', e.target.value)}>
                    {GENDER_OPTIONS.map(g => <option key={g} value={g}>{g.charAt(0).toUpperCase() + g.slice(1)}</option>)}
                  </select>
                </Field>
                <Field label="Date of Birth">
                  <input className="erp-input" type="date" value={personal.dateOfBirth} onChange={e => sp('dateOfBirth', e.target.value)} />
                </Field>
                <Field label="Blood Group">
                  <select className="erp-input" value={personal.bloodGroup} onChange={e => sp('bloodGroup', e.target.value)}>
                    <option value="">— Select —</option>
                    {BLOOD_GROUPS.map(b => <option key={b} value={b}>{b}</option>)}
                  </select>
                </Field>
              </div>
            </div>
          )}

          {/* STEP 2: Academic */}
          {step === 2 && (
            <div className="flex flex-col gap-5 animate-fade-in">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Field label="Target Class" required helpText="Select the class to enroll into">
                  <select className="erp-input" value={academic.className} onChange={e => sa('className', e.target.value)}>
                    <option value="">— Select Class —</option>
                    {classes.map((c: any) => <option key={c.id} value={c.name}>{c.name}</option>)}
                  </select>
                </Field>
                <Field label="Section Allocation" helpText="Auto-filtered based on selected class">
                  <select className="erp-input" value={academic.section} onChange={e => sa('section', e.target.value)} disabled={!academic.className}>
                    <option value="">— Unassigned —</option>
                    {availableSections.map((s: any) => <option key={s.id} value={s.name}>{s.name}</option>)}
                  </select>
                </Field>
                <Field label="Date of Admission">
                  <input className="erp-input" type="date" value={academic.dateOfAdmission} onChange={e => sa('dateOfAdmission', e.target.value)} />
                </Field>
              </div>
            </div>
          )}

          {/* STEP 3: Address & Guardian */}
          {step === 3 && (
            <div className="flex flex-col gap-6 animate-fade-in">

              {/* ── ADDRESS ── */}
              <div className="space-y-4">
                <h3 className="font-bold text-sm text-[var(--foreground)] border-b border-[var(--border)] pb-2">Address Details</h3>
                
                <div className="bg-[var(--surface-raised)] border border-[var(--border)] rounded-xl p-4">
                  <h4 className="text-xs font-bold text-[var(--foreground)] mb-3">Permanent Address</h4>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                    <Field label="Province" required><input className="erp-input text-sm" value={address.province} onChange={e => sd('province', e.target.value)} placeholder="Bagmati" /></Field>
                    <Field label="District" required><input className="erp-input text-sm" value={address.district} onChange={e => sd('district', e.target.value)} placeholder="Kathmandu" /></Field>
                    <Field label="Municipality" required><input className="erp-input text-sm" value={address.municipality} onChange={e => sd('municipality', e.target.value)} placeholder="KTM Metro" /></Field>
                    <Field label="Ward No"><input className="erp-input text-sm" type="number" value={address.wardNo} onChange={e => sd('wardNo', e.target.value)} placeholder="01" /></Field>
                    <Field label="Tole"><input className="erp-input text-sm" value={address.tole} onChange={e => sd('tole', e.target.value)} placeholder="Thamel" /></Field>
                    <Field label="House No"><input className="erp-input text-sm" value={address.houseNo} onChange={e => sd('houseNo', e.target.value)} placeholder="H-123" /></Field>
                    <Field label="Post Code"><input className="erp-input text-sm" value={address.postCode} onChange={e => sd('postCode', e.target.value)} placeholder="44600" /></Field>
                    <Field label="Country"><input className="erp-input text-sm" value={address.country} onChange={e => sd('country', e.target.value)} disabled /></Field>
                  </div>
                </div>

                <div className="flex items-center gap-2 px-1">
                  <input type="checkbox" id="sameAddress" className="w-4 h-4 text-[var(--primary)] rounded cursor-pointer"
                    checked={address.isTemporarySame} onChange={e => sd('isTemporarySame', e.target.checked)} />
                  <label htmlFor="sameAddress" className="text-sm font-medium text-[var(--foreground)] cursor-pointer">Temporary Address is same as Permanent Address</label>
                </div>

                {!address.isTemporarySame && (
                  <div className="bg-[var(--surface-raised)] border border-[var(--border)] rounded-xl p-4 animate-fade-in">
                    <h4 className="text-xs font-bold text-[var(--foreground)] mb-3">Temporary Address</h4>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                      <Field label="Province" required><input className="erp-input text-sm" value={address.tempProvince} onChange={e => sd('tempProvince', e.target.value)} /></Field>
                      <Field label="District" required><input className="erp-input text-sm" value={address.tempDistrict} onChange={e => sd('tempDistrict', e.target.value)} /></Field>
                      <Field label="Municipality" required><input className="erp-input text-sm" value={address.tempMunicipality} onChange={e => sd('tempMunicipality', e.target.value)} /></Field>
                      <Field label="Ward No"><input className="erp-input text-sm" value={address.tempWardNo} onChange={e => sd('tempWardNo', e.target.value)} /></Field>
                      <Field label="Tole"><input className="erp-input text-sm" value={address.tempTole} onChange={e => sd('tempTole', e.target.value)} /></Field>
                      <Field label="House No"><input className="erp-input text-sm" value={address.tempHouseNo} onChange={e => sd('tempHouseNo', e.target.value)} /></Field>
                    </div>
                  </div>
                )}
              </div>

              {/* ── GUARDIAN ── */}
              <div className="space-y-4">
                <div className="flex items-center justify-between border-b border-[var(--border)] pb-2">
                  <h3 className="font-bold text-sm text-[var(--foreground)]">Guardian Information</h3>
                  <div className="flex bg-[var(--surface-raised)] p-0.5 rounded-lg border border-[var(--border)]">
                    <button className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${guardianMode === 'new' ? 'bg-[var(--card-bg)] text-[var(--foreground)] shadow-sm' : 'text-[var(--foreground-muted)] hover:text-[var(--foreground)]'}`} onClick={() => setGuardianMode('new')}>Register New</button>
                    <button className={`px-3 py-1 text-xs font-semibold rounded-md transition-colors ${guardianMode === 'existing' ? 'bg-[var(--card-bg)] text-[var(--primary)] shadow-sm' : 'text-[var(--foreground-muted)] hover:text-[var(--foreground)]'}`} onClick={() => setGuardianMode('existing')}>Link Existing</button>
                  </div>
                </div>

                {guardianMode === 'existing' ? (
                  <div className="bg-[var(--surface-raised)] border border-[var(--border)] rounded-xl p-4 flex flex-col gap-4 animate-fade-in">
                    <div>
                      <Field label="Search Parent" helpText="Search by Email, Phone, or Name">
                        <div className="relative">
                          <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--foreground-muted)]" size={16} />
                          <input className="erp-input pl-10" value={parentSearch} onChange={e => setParentSearch(e.target.value)} placeholder="Start typing..." />
                        </div>
                      </Field>
                      
                      {parentSearch && (
                        <div className="mt-2 bg-[var(--card-bg)] border border-[var(--border)] rounded-lg overflow-hidden max-h-48 overflow-y-auto">
                          {isSearchingParents ? (
                            <div className="p-3 text-xs text-[var(--foreground-muted)] text-center animate-pulse">Searching...</div>
                          ) : parents.length === 0 ? (
                            <div className="p-3 text-xs text-[var(--foreground-muted)] text-center">No parents found.</div>
                          ) : (
                            parents.map((p: any) => (
                              <div key={p.id} onClick={() => setSelectedParentUser(p)}
                                className={`p-3 border-b border-[var(--border)] cursor-pointer hover:bg-[var(--surface-raised)] transition-colors flex items-center justify-between ${selectedParentUser?.id === p.id ? 'bg-[var(--primary-light)]' : ''}`}>
                                <div>
                                  <div className="font-semibold text-sm text-[var(--foreground)]">{p.user?.name ?? p.name}</div>
                                  <div className="text-xs text-[var(--foreground-muted)]">{p.user?.email ?? p.email} | {p.user?.phone ?? p.phone}</div>
                                </div>
                                {selectedParentUser?.id === p.id && <CheckCircle size={16} className="text-[var(--primary)]" />}
                              </div>
                            ))
                          )}
                        </div>
                      )}
                    </div>
                    {selectedParentUser && (
                      <div className="p-3 bg-emerald-50 border border-emerald-200 rounded-lg flex gap-3 text-emerald-900">
                        <CheckCircle size={18} className="text-emerald-500 shrink-0 mt-0.5" />
                        <div>
                          <p className="text-sm font-semibold">Parent Linked Successfully</p>
                          <p className="text-xs opacity-80 mt-0.5">This student will be attached to {selectedParentUser.user?.name ?? selectedParentUser.name}'s account.</p>
                        </div>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="flex flex-col gap-4 animate-fade-in">
                    <p className="text-xs text-[var(--foreground-muted)]">Please fill at least one parent's information. The primary parent is used for the portal account.</p>
                    
                    {(['father', 'mother', 'guardian'] as const).map(role => (
                      <div key={role} className="rounded-xl border border-[var(--border)] p-4 bg-[var(--surface-raised)]">
                        <h3 className="font-semibold text-sm text-[var(--foreground)] mb-3 capitalize">{role} Details</h3>
                        <div className="grid grid-cols-2 gap-3">
                          {['name', 'email', 'phone', role === 'guardian' ? 'relation' : 'occupation'].map(field => (
                            <Field key={field} label={field.charAt(0).toUpperCase() + field.slice(1)}>
                              <input
                                className="erp-input text-sm"
                                type={field === 'email' ? 'email' : 'text'}
                                value={(guardian[role] as any)[field] ?? ''}
                                onChange={e => setGuardian(g => ({
                                  ...g,
                                  [role]: { ...g[role], [field]: e.target.value },
                                }))}
                              />
                            </Field>
                          ))}
                        </div>
                      </div>
                    ))}

                    <div className="bg-[var(--card-bg)] border border-[var(--border)] p-4 rounded-xl">
                      <Field label="Emergency Contact (SMS/Calls)" required>
                        <select className="erp-input text-sm" value={guardian.emergencyContact} onChange={e => setGuardian(prev => ({...prev, emergencyContact: e.target.value}))}>
                          <option value="father">Father</option>
                          <option value="mother">Mother</option>
                          <option value="guardian">Guardian</option>
                        </select>
                      </Field>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* STEP 4: Background & Medical */}
          {step === 4 && (
            <div className="flex flex-col gap-6 animate-fade-in">
              <div className="space-y-4">
                <h3 className="font-bold text-sm text-[var(--foreground)] border-b border-[var(--border)] pb-2">Medical History & Information</h3>
                
                <div>
                  <label className="text-xs font-semibold text-[var(--foreground-muted)] uppercase tracking-wide block mb-2">Known Allergies</label>
                  <div className="flex flex-wrap gap-2">
                    {COMMON_ALLERGIES.map(a => {
                      const active = background.allergies.includes(a)
                      return (
                        <button key={a} type="button" onClick={() => toggleAllergy(a)}
                          className={`px-3 py-1.5 text-xs font-semibold border rounded-full transition-colors ${active ? 'bg-[var(--danger)] text-white border-[var(--danger)]' : 'bg-[var(--surface-raised)] border-[var(--border)] text-[var(--foreground)] hover:border-[var(--foreground-muted)]'}`}>
                          {a}
                        </button>
                      )
                    })}
                  </div>
                  <div className="mt-3">
                    <Field label="Other Allergies"><input className="erp-input text-sm" value={background.allergiesOther} onChange={e => setBackground(b => ({...b, allergiesOther: e.target.value}))} placeholder="Specify if any..." /></Field>
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <Field label="Specific Ailments" helpText="e.g., Asthma, ADHD, Diabetes">
                    <textarea className="erp-input min-h-[80px] p-2 text-sm" value={background.specificAilments} onChange={e => setBackground(b => ({...b, specificAilments: e.target.value}))} />
                  </Field>
                  <Field label="Surgery / Medical History">
                    <textarea className="erp-input min-h-[80px] p-2 text-sm" value={background.surgeryHistory} onChange={e => setBackground(b => ({...b, surgeryHistory: e.target.value}))} />
                  </Field>
                  <Field label="Special Physical Instructions">
                    <textarea className="erp-input min-h-[80px] p-2 text-sm" value={background.specialInstructions} onChange={e => setBackground(b => ({...b, specialInstructions: e.target.value}))} />
                  </Field>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold text-sm text-[var(--foreground)] border-b border-[var(--border)] pb-2">Schooling Background</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <Field label="Previously Attended School?">
                    <select className="erp-input text-sm" value={background.previousSchooling} onChange={e => setBackground(b => ({...b, previousSchooling: e.target.value}))}>
                      <option>No</option><option>Yes</option>
                    </select>
                  </Field>
                  <Field label="Family / Kin currently enrolled?">
                    <select className="erp-input text-sm" value={background.familyAtThisSchool} onChange={e => setBackground(b => ({...b, familyAtThisSchool: e.target.value}))}>
                      <option>No</option><option>Yes</option>
                    </select>
                  </Field>
                </div>
              </div>
            </div>
          )}

          {/* STEP 5: Documents */}
          {step === 5 && (
            <div className="flex flex-col gap-6 animate-fade-in">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                
                {/* Formal Inputs Array */}
                {[
                  { key: 'profileImage', label: 'Student Passport Photo', req: true, accept: 'image/*' },
                  { key: 'birthCertificate', label: 'Birth Certificate', req: true, accept: '.pdf,image/*' },
                  { key: 'parentId', label: 'Parent/Guardian ID (Citizenship/Passport)', req: true, accept: '.pdf,image/*' },
                  { key: 'prevAcademicCert', label: 'Previous Academic Record', req: false, accept: '.pdf,image/*' },
                  { key: 'transferCert', label: 'Transfer Certificate', req: false, accept: '.pdf,image/*' },
                  { key: 'parentPhoto', label: 'Parent/Guardian Photo', req: false, accept: 'image/*' },
                ].map((item) => (
                  <div key={item.key} className="border border-[var(--border)] bg-[var(--surface-raised)] rounded-xl p-4 flex flex-col gap-2">
                    <div className="flex items-center justify-between">
                      <label className="text-sm font-bold text-[var(--foreground)]">
                        {item.label} {item.req && <span className="text-[var(--danger)]">*</span>}
                      </label>
                      {!item.req && <span className="text-[10px] uppercase font-semibold text-[var(--foreground-muted)] border border-[var(--border)] px-1.5 rounded bg-[var(--card-bg)]">Optional</span>}
                    </div>
                    
                    <div className="relative group overflow-hidden border-2 border-dashed border-[var(--border)] rounded-lg hover:border-[var(--primary)] transition-colors h-24 flex items-center justify-center bg-[var(--card-bg)] cursor-pointer">
                      <input 
                        type="file" accept={item.accept} className="absolute inset-0 opacity-0 cursor-pointer w-full h-full z-10"
                        onChange={(e) => {
                          const file = e.target.files?.[0]
                          if(file) {
                            sDocs(item.key as DocKey, file)
                            if (item.key === 'profileImage') setProfilePreview(URL.createObjectURL(file))
                          }
                        }}
                      />
                      {(docs[item.key as DocKey]) ? (
                        item.key === 'profileImage' && profilePreview ? (
                          <img src={profilePreview} className="w-full h-full object-cover" alt="preview" />
                        ) : (
                          <div className="flex flex-col items-center text-emerald-600">
                            <CheckCircle size={24} />
                            <span className="text-xs font-semibold mt-1 truncate max-w-[150px] px-2">{docs[item.key as DocKey]?.name}</span>
                          </div>
                        )
                      ) : (
                        <div className="flex flex-col items-center text-[var(--foreground-muted)] group-hover:text-[var(--primary)] transition-colors">
                          <UploadCloud size={24} />
                          <span className="text-xs font-semibold mt-1">Click to browse</span>
                        </div>
                      )}
                    </div>
                  </div>
                ))}

              </div>
            </div>
          )}

          {/* STEP 6: Review */}
          {step === 6 && (
            <div className="flex flex-col gap-5 animate-fade-in">
              <div className="bg-[var(--surface-raised)] border border-[var(--border)] rounded-xl p-5 break-words">
                <h3 className="font-bold text-[var(--foreground)] border-b border-[var(--border)] pb-2 mb-3">Admission Preview</h3>
                
                <div className="grid grid-cols-2 gap-y-4 gap-x-8 text-sm">
                  <div>
                    <p className="text-xs text-[var(--foreground-muted)] font-semibold uppercase">Student Name</p>
                    <p className="font-medium text-[var(--foreground)]">{personal.firstName} {personal.surname}</p>
                  </div>
                  <div>
                    <p className="text-xs text-[var(--foreground-muted)] font-semibold uppercase">Target Class</p>
                    <p className="font-medium text-[var(--foreground)]">{academic.className} {academic.section && `(Sec ${academic.section})`}</p>
                  </div>
                  <div>
                    <p className="text-xs text-[var(--foreground-muted)] font-semibold uppercase">Email & Phone</p>
                    <p className="font-medium text-[var(--foreground)]">{personal.email} / {personal.phone || 'N/A'}</p>
                  </div>
                  <div>
                    <p className="text-xs text-[var(--foreground-muted)] font-semibold uppercase">Guardian Mapping</p>
                    <p className="font-medium text-[var(--foreground)]">
                      {guardianMode === 'existing' && selectedParentUser ? `Linked to ${selectedParentUser.user?.name ?? selectedParentUser.name}` : `New Record (${guardian.emergencyContact} as primary)`}
                    </p>
                  </div>
                  <div className="col-span-2">
                    <p className="text-xs text-[var(--foreground-muted)] font-semibold uppercase">Documents attached</p>
                    <div className="flex gap-2 flex-wrap mt-1">
                      {Object.entries(docs).filter(([_,v]) => v !== null).map(([k]) => (
                        <span key={k} className="px-2 py-1 text-[10px] font-bold uppercase rounded bg-emerald-100 text-emerald-800 border border-emerald-200">{k}</span>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

              <label className="flex items-start gap-3 p-4 border border-[var(--border)] rounded-xl cursor-pointer hover:bg-[var(--surface-raised)] transition-colors">
                <input type="checkbox" checked={declaration} onChange={e => setDeclaration(e.target.checked)} className="w-5 h-5 rounded border-gray-300 text-[var(--primary)] mt-0.5" />
                <div>
                  <p className="font-bold text-sm text-[var(--foreground)]">Information Declaration</p>
                  <p className="text-xs text-[var(--foreground-muted)] mt-0.5 leading-relaxed">
                    I / We agree to the rules and regulations of the institution and confirm that all information provided in this admission form is accurate. I understand that the admission number and core IDs will be permanently generated upon submission.
                  </p>
                </div>
              </label>

              {error && <div className="p-3 bg-[var(--danger-bg)] text-[var(--danger-text)] text-sm rounded-lg flex items-center gap-2 font-medium border border-[var(--danger)] border-opacity-20"><AlertCircle size={16} />{error}</div>}
            </div>
          )}

        </div>

        {/* ── Footer / Actions ── */}
        <div className="px-6 py-4 border-t border-[var(--border)] shrink-0 flex items-center justify-between bg-[var(--card-bg)] rounded-b-2xl">
          <button onClick={prev} disabled={step === 1} className="btn-ghost text-sm font-semibold flex items-center gap-1.5 px-4 disabled:opacity-0 disabled:pointer-events-none">
            <ChevronLeft size={16} /> Back
          </button>
          
          {step < STEPS.length ? (
            <button onClick={next} className="btn-primary text-sm font-semibold flex items-center gap-1.5 px-6">
              Next Step <ChevronRight size={16} />
            </button>
          ) : (
            <button onClick={handleSubmit} disabled={isLoading || !declaration} className="btn-primary text-sm font-semibold flex items-center gap-2 px-8 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50">
              {isLoading ? <span className="animate-pulse">Processing Registration…</span> : <><CheckCircle size={16} /> Submit Admission</>}
            </button>
          )}
        </div>

      </div>
    </div>
  )
}
